# fly.toml app configuration file generated for ggbot on 2024-02-27T23:26:12+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ggbot'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'
[env]
PORT = '8080'
[[services]]
  internal_port = 8000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
[[vm]]
  size = 'shared-cpu-1x'